spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: sampleoneid
          uri: lb://sampleone
          predicates:
            - Path=/sampleone/**
          filters:
            - RewritePath=/sampleone/(?<path>.*), /$\{path}
        - id: order-service-eureka-clientid
          uri: lb://order-service-eureka-client
          predicates:
            - Path=/order-service-eureka-client/**
          filters:
            - RewritePath=/order-service-eureka-client/(?<path>.*), /$\{path}

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

